### ISSUE TITLE
Create msk connector with an existing cluster

### ISSUE THREAD

**Issue by kaoscore** [clowdhaus/terraform-aws-msk-kafka-cluster#2]
**Is your feature request related to a problem? Please describe.**
How can we create the msk connector in terraform with an existing msk cluster?

**Comment by bryantbiggs** [comment]
hi @kaoscore - I'm not sure I follow. have you checked the examples? https://github.com/clowdhaus/terraform-aws-msk-kafka-cluster/blob/main/examples/connect/main.tf#L139-L154

**Comment by kaoscore** [comment]
Yes I do, but this example creates the cluster and the connector at the same time, I need to create the connect only.

**Comment by bryantbiggs** [comment]
by using the resource independently? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mskconnect_custom_plugin

**Comment by kaoscore** [comment]
Yes, and also using this https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mskconnect_worker_configuration

I dont see how relate an existing MSK cluster with a new MSK connector

**Comment by bryantbiggs** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/20942

**Comment by kaoscore** [comment]
This feature aws_kafkaconnect_connector  is still under construction?? or I can use it
